version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     volumes:
       - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
     environment:
       MYSQL_ROOT_PASSWORD: pssarkis2019pso
       MYSQL_DATABASE: wordpress
       MYSQL_USER: pssarkis
       MYSQL_PASSWORD: psaicoskipso2019

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: pssarkis
       WORDPRESS_DB_PASSWORD: psaicoskipso2019
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
